[2024-03-09T16:20:23.568+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl2.truncate_mrr_stg manual__2024-03-09T16:20:14.542783+00:00 [queued]>
[2024-03-09T16:20:23.742+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl2.truncate_mrr_stg manual__2024-03-09T16:20:14.542783+00:00 [queued]>
[2024-03-09T16:20:23.744+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 6
[2024-03-09T16:20:23.882+0000] {taskinstance.py:2214} INFO - Executing <Task(PostgresOperator): truncate_mrr_stg> on 2024-03-09 16:20:14.542783+00:00
[2024-03-09T16:20:23.917+0000] {standard_task_runner.py:60} INFO - Started process 2359 to run task
[2024-03-09T16:20:23.917+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'etl2', 'truncate_mrr_stg', 'manual__2024-03-09T16:20:14.542783+00:00', '--job-id', '232', '--raw', '--subdir', 'DAGS_FOLDER/etl2.py', '--cfg-path', '/tmp/tmpjat76hkd']
[2024-03-09T16:20:23.947+0000] {standard_task_runner.py:88} INFO - Job 232: Subtask truncate_mrr_stg
[2024-03-09T16:20:24.711+0000] {task_command.py:423} INFO - Running <TaskInstance: etl2.truncate_mrr_stg manual__2024-03-09T16:20:14.542783+00:00 [running]> on host 3b9d9f11e4f2
[2024-03-09T16:20:25.135+0000] {abstractoperator.py:707} ERROR - Exception rendering Jinja template for task 'truncate_mrr_stg', field 'sql'. Template: 'truncate_mrr_stg.sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/abstractoperator.py", line 699, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 171, in render_template
    template = jinja_env.get_template(value)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: truncate_mrr_stg.sql
[2024-03-09T16:20:25.143+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2357, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2495, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2907, in render_templates
    original_task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 1241, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/abstractoperator.py", line 699, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 171, in render_template
    template = jinja_env.get_template(value)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: truncate_mrr_stg.sql
[2024-03-09T16:20:25.193+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=etl2, task_id=truncate_mrr_stg, execution_date=20240309T162014, start_date=20240309T162023, end_date=20240309T162025
[2024-03-09T16:20:25.327+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 232 for task truncate_mrr_stg (truncate_mrr_stg.sql; 2359)
[2024-03-09T16:20:25.420+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-09T16:20:25.565+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
